USE [master]
GO

/****** Object:  Database [FuruiFukuIncDB]    Script Date: 15/07/2024 02:14:16 a. m. ******/
CREATE DATABASE [FuruiFukuIncDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FuruiFukuIncDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\FuruiFukuIncDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FuruiFukuIncDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\FuruiFukuIncDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FuruiFukuIncDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FuruiFukuIncDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FuruiFukuIncDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FuruiFukuIncDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FuruiFukuIncDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FuruiFukuIncDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FuruiFukuIncDB] SET  MULTI_USER 
GO

ALTER DATABASE [FuruiFukuIncDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FuruiFukuIncDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FuruiFukuIncDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FuruiFukuIncDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FuruiFukuIncDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FuruiFukuIncDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FuruiFukuIncDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FuruiFukuIncDB] SET  READ_WRITE 
GO




USE [FuruiFukuIncDB]
GO

/****** Object:  Table [dbo].[Usuario]    Script Date: 15/07/2024 02:13:01 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Usuario](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](max) NOT NULL,
	[Nombre] [nvarchar](max) NOT NULL,
	[Edad] [int] NOT NULL,
	[FechaIngreso] [nvarchar](max) NOT NULL,
	[ImporteTotalVentas] [float] NOT NULL,
	[Puesto] [nvarchar](max) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

USE [FuruiFukuIncDB]
GO

/****** Object:  Table [dbo].[Ventas]    Script Date: 15/07/2024 02:13:20 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Ventas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DescripcionArticulo] [nvarchar](max) NOT NULL,
	[FechaVenta] [nvarchar](max) NOT NULL,
	[ImporteVenta] [float] NOT NULL,
	[EstatusVenta] [nvarchar](max) NOT NULL,
	[EstatusSupervision] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Ventas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

